name: testcicd

on: 
  push:
    branches:    
      - main
      
jobs:
  build:
    name: testing the sample workflow cicd
    runs-on: ubuntu-latest
  
    steps:
      - name: printing some message as indication of success
        run: |
          echo "HELLO"
          echo "WORLD"
